<a href="https://colab.research.google.com/github/elvoza/Curso-Introductorio-a-Python/blob/main/Sesi%C3%B3n_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="120px" src="https://www.udea.edu.co/wps/wcm/connect/udea/df55724e-3ebc-46c6-b608-fb9206b3fede/facultad-economicas.png?MOD=AJPERES&CVID=nc5zPyj" align="Center" hspace="10px" vspace="10px"></p>


#***Python I - Introducción a modelos económicos y financieros con Python***

---


#**Sesión 3**
# Docente: *Cristian Ruiz Parra*

---
Contenido de la sesión
- Introducción a Numpy
- Operaciones con arreglos matriciales
- principales funciones
- Taller practico

# **Numpy (np)**

NumPy (Numerical Python) es la biblioteca fundamental para computación científica en Python. Proporciona un objeto de arreglo de datos multidimensional de alto rendimiento y herramientas para trabajar con estos "arrays o arreglos".

Primer paso para acceder a Numpy es importarlo

In [ ]:
import numpy as np

Recuerda llamarlo con el alias (np) para simplificar el llamar las funciones propias de Numpy

In [ ]:
import numpy as np

# 📦 CREACIÓN DE ARRAYS NUMPY
def demostracion_arrays():
    # Desde lista Python
    lista_python = [1, 2, 3, 4, 5]
    array_numpy = np.array(lista_python)

    print("🎯 COMPARACIÓN LISTA vs ARRAY:")
    print(f"Lista Python: {lista_python} (tipo: {type(lista_python)})")
    print(f"Array NumPy:  {array_numpy} (tipo: {type(array_numpy)})")
    print(f"Tipo datos array: {array_numpy.dtype}")
    print(f"Forma del array: {array_numpy.shape}")
    print(f"Dimensiones: {array_numpy.ndim}D")

# Ejecutar demostración
demostracion_arrays()

🎯 COMPARACIÓN LISTA vs ARRAY:
Lista Python: [1, 2, 3, 4, 5] (tipo: <class 'list'>)
Array NumPy:  [1 2 3 4 5] (tipo: <class 'numpy.ndarray'>)
Tipo datos array: int64
Forma del array: (5,)
Dimensiones: 1D


# ¿Por que usar Numpy en lugar de las listas de Python?

La respuesta a esta pregunta es por eficiencia computacional, los algoritmos de Numpy estan implementados en "C" y se encuentran optimizados

In [ ]:
import time

def comparacion_velocidad():
    # Datos de ejemplo
    datos = list(range(1000000))
    array_numpy = np.array(datos)

    # Operación con lista Python
    inicio_lista = time.time()
    resultado_lista = [x * 2 for x in datos]
    tiempo_lista = time.time() - inicio_lista

    # Operación con NumPy
    inicio_numpy = time.time()
    resultado_numpy = array_numpy * 2
    tiempo_numpy = time.time() - inicio_numpy

    print("⚡ COMPARACIÓN DE VELOCIDAD:")
    print(f"Lista Python: {tiempo_lista:.6f} segundos")
    print(f"NumPy: {tiempo_numpy:.6f} segundos")
    print(f"NumPy es {tiempo_lista/tiempo_numpy:.1f}x más rápido")
    print(datos[0:10])
    print(array_numpy[0:10])
    print(resultado_lista[0:10])
    print(resultado_numpy[0:10])

comparacion_velocidad()

⚡ COMPARACIÓN DE VELOCIDAD:
Lista Python: 0.060808 segundos
NumPy: 0.005975 segundos
NumPy es 10.2x más rápido
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]


# **Arreglos de datos**

Existen multiples formas de organizar la información en función de la cantidad de dimensiones de los datos, que podria verse también si existe mayor interacción entre diferentes cantidades de variables y estructuras temporales

¿Cómo conocemos estos arreglos en función de sus dimensiones?

0D:

1D:

2D:

3D:

4D:

## 1D array (vector)

un arreglo unidimensional es una colecion de tipos de datos los cuales se encuntran indexados ( tal y como las listas ). A diferencia de las listas, los arreglos 1D ( y en general los arreglos de cualquier dimension ) solo pueden contener un tipo de dato.

Los arreglos de python soportan indexacion y slicing

para crear un arreglo 1D de python , podemos usar una lista de numpy


In [ ]:
v = np.array([1,2,2,5,2.6,5,6,7,3]) #creacion de un arreglo 1D de numpy
print(type(v))
v #Veamos el vector y a que clase pertenece (esto es , veamos que tipo de dato es)

<class 'numpy.ndarray'>


array([1. , 2. , 2. , 5. , 2.6, 5. , 6. , 7. , 3. ])

In [ ]:
#indexacion
v[0], v[1] , v[-1] , v[4]

(np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(2.6))

**Formato para llamar subarreglos (Slicing)**

Para llamar una parte de un Arreglo en 1D tenemos el fotmato siguiente:

Nombre del arreglo[Elmento inicial:Elemento final:paso]



In [ ]:
#slicing [indice_inicial:indice_fianl:paso]
v[0:7:2], v[::-1] , v[1::3] , v[5::]

(array([1. , 2. , 2.6, 6. ]),
 array([3. , 7. , 6. , 5. , 2.6, 5. , 2. , 2. , 1. ]),
 array([2. , 2.6, 7. ]),
 array([5., 6., 7., 3.]))

**Lista de elementos**

Nombre del arreglo[[Elemento1, elmento2, elemento3,... elementon]]

In [ ]:
# otras formas de hacer indexing (usar una lista para hacer indexing)
v[[1,3,5,6]]

array([2., 5., 5., 6.])

**Formato Buleano**
Aquí describiremos que posiciones queremos que conformen nuestro nuevo arreglo

Nombre del arreglo[[(True or false, True or false, True or false, True or false... True or false]]

In [ ]:
#Indexacion usando tipos buleanos
v[[True , True , False, False, True, True, False, False, False]]

array([1. , 2. , 2.6, 5. ])

In [ ]:
#Indexacion usando tipos buleanos
v > 4

array([False, False, False,  True, False,  True,  True,  True, False])

In [ ]:
#Indexacion usando tipos buleanos
v[v > 4]

array([5., 5., 6., 7.])

In [ ]:
print(v.shape) #atributo shape del arreglo de numpy (Formato de la matrix)
print(v.dtype) #atributo dtype (Tipos de datos que conforman el arreglo)
print(v.size) #atributo size (cantidad de elementos)
print(v.ndim) #atributo ndim (Dimensiones del arreglo)

(9,)
float64
9
1


## 2D arrays

```
# Tiene formato de código
```



Como se menciono antes, es posible crear arreglos de mayor dimension. en este caso , veamos los arreglos 2D (tambien conocidos como matrices)

In [ ]:
#creacion de un arreglo 2D (matriz) usando una lista de python
entradas = [
            [2,6,4,8,9],
            [2,6,7,9,2.3],
            [5,6,3.,4,2.,],
            [9,0,5,3,6,],
            [3.6,2.7,9.8,2,4]
            ]

In [ ]:
#creacion de un arreglo 2D (matriz) usando una lista de python
M = np.array(entradas)
M

array([[2. , 6. , 4. , 8. , 9. ],
       [2. , 6. , 7. , 9. , 2.3],
       [5. , 6. , 3. , 4. , 2. ],
       [9. , 0. , 5. , 3. , 6. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [ ]:
#Indexacion en arreglos matriciales
M[0,0] , M[4,-1] , M[4,4]

(np.float64(2.0), np.float64(4.0), np.float64(4.0))

In [ ]:
#Slicing en arreglos matriciales
# Filas: desde 0 hasta 5, paso 2 | Columna:  0 hasta la 4
M[0:6:2, 0:3]

array([[2. , 6. , 4. ],
       [5. , 6. , 3. ],
       [3.6, 2.7, 9.8]])

In [ ]:
#Slicing en arreglos matriciales
# # Filas: 0→6 paso 2 | Columnas: 0→6 paso 2
M[0:6:2, 0:6:2]

array([[2. , 4. , 9. ],
       [5. , 3. , 2. ],
       [3.6, 9.8, 4. ]])

In [ ]:
#Slicing en arreglos matriciales
# Filas: 0→6 paso 2 | Columnas: TODAS
M[0:6:2, :]

array([[2. , 6. , 4. , 8. , 9. ],
       [5. , 6. , 3. , 4. , 2. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [ ]:
#Slicing en arreglos matriciales
# Filas: TODAS | Columnas: Ultima
M[0:, -1]


array([9. , 2.3, 2. , 6. , 4. ])

In [ ]:
#Slicing en arreglos matriciales
#Filas Todas | columas todas con paso 3
M[:, 0:-1:3]

array([[2. , 8. ],
       [2. , 9. ],
       [5. , 4. ],
       [9. , 3. ],
       [3.6, 2. ]])

In [ ]:
#Otras formas de indexing usando listas de python
M[:,[0,2,4]]

array([[2. , 4. , 9. ],
       [2. , 7. , 2.3],
       [5. , 3. , 2. ],
       [9. , 5. , 6. ],
       [3.6, 9.8, 4. ]])

In [ ]:
#Otras formas de indexing (termino a termino)
index = [[2,2],[0,0]], [[2,2],[0,0]]
M[index]

array([[3., 3.],
       [2., 2.]])

In [ ]:
#Indexacion usando tipos buleanos
M > 5

array([[False,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [False, False,  True, False, False]])

In [ ]:
#Indexacion usando tipos buleanos
M[M > 5]

array([6. , 8. , 9. , 6. , 7. , 9. , 6. , 9. , 6. , 9.8])

In [ ]:
print(M.shape) #atributo shape del arreglo de numpy
print(M.dtype) #atributo dtype
print(M.size) #atributo size
print(M.ndim) #atributo ndim

(5, 5)
float64
25
2


Numpy tiene muchas funciones para crear arreglos

In [ ]:
# Creación de un array de zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
# Creación de un array de unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creación de un array de una costante
np.full(5 , 3)

array([3, 3, 3, 3, 3])

In [ ]:
np.full((3,3,3), 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [ ]:
# Creación de la matriz indentidad de 2x2.
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Crea un vector desde el número inicial 4 hasta el final 10 de 0,2 en 0,2
np.arange(4,10,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [ ]:
# Crea un vector de diez valores espaciados la función encuentra el paso
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [ ]:
# Creación de un arreglo de valores aleatorios dados por una distribucion
#uniforme en el rango (0,1)
np.random.random(10)

array([0.73623658, 0.51370272, 0.07941719, 0.12944331, 0.03192888,
       0.34506528, 0.08902141, 0.08268152, 0.43762398, 0.77135962])

In [ ]:
np.random.random((2,2))

array([[0.26079813, 0.82823923],
       [0.06448793, 0.06129111]])

In [ ]:
# Creación arreglo de valores aleatorios dados por una distribucion normal
#loc: Media de la distribución (μ) - default: 0.0
#scale: Desviación estándar (σ) - default: 1.0
#size: Forma del array de salida (int o tupla) - default: None

np.random.normal(loc=5, scale=1, size=10)

array([5.54730031, 5.72995806, 4.24132714, 4.44741354, 3.61776274,
       4.38833216, 4.43500895, 5.37255682, 5.27866381, 4.48210496])

In [ ]:
np.random.normal(loc=0, scale=1, size=(3,3))

array([[-1.31358478,  1.00590217, -1.14564481],
       [ 0.24920212,  0.23690745, -0.51320557],
       [-0.64837712, -1.16955595,  1.02789509]])

In [ ]:
# Creación de una arreglo de números enteros aleatorios dados por una distribucion uniforme en el rango dado
np.random.randint(low = 2, high=10, size=10)

array([2, 5, 8, 5, 8, 2, 3, 4, 4, 9])

In [ ]:
np.random.randint(low = 2, high=10, size=(4,4))

array([[5, 7, 4, 8],
       [8, 6, 9, 7],
       [3, 4, 5, 5],
       [6, 5, 2, 8]])

## Ejercicios

\1) Crea una matriz de 3 x 3 con todos los valores true

2) Reemplace todos los numeros impares por -1
```
Input

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```


3) Convertir un array de 1D en uno de 2D con dos filas con la misma cantidad de elementos



```
Input:

arr = np.arange(16)
```

ayuda: Investigar el metodo `reshape ` que tienen los arreglos de numpy


In [ ]:
help(np.reshape)

4) Convierte los vectores fila a y b en un vector columna (Apila verticalmente los vectores a y b)

```
Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

ayuda: investigar las funciones np.vstack , np.hstack

In [ ]:

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
a.reshape(1,-1,)

In [ ]:
ab=np.hstack((a,b))
ab

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

5) Identifica los elementos iguales en a y b



```
Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

ayuda: investigar la funcion np.where


6) Intercambiar las columnas 1 y 2 en el array arr

arr = np.arange(9).reshape(3,3)




```
arr = np.arange(9).reshape(3,3)
```



In [ ]:
arr = np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Operaciones basicas entre entre arreglos del mismo tamaño

Las operaciones basicas entre arreglos se dan elemento a elemnto

In [ ]:
#definamos los dos arreglos
v = np.random.randint(low = 2, high=10, size=10)
w = np.random.randint(low = 2, high=10, size=10)
v,w

(array([4, 4, 5, 6, 4, 8, 4, 3, 7, 3]), array([3, 6, 6, 4, 9, 5, 4, 5, 4, 8]))

In [ ]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v , w - v

(array([11, 14, 10, 12, 14, 16,  7, 10, 11, 17]),
 array([ 7, -2,  0,  0,  0,  2,  3, -2, -5, -1]))

In [ ]:
#multiplicacion y division
w*v , w/v

(array([18, 48, 25, 36, 49, 63, 10, 24, 24, 72]),
 array([4.5       , 0.75      , 1.        , 1.        , 1.        ,
        1.28571429, 2.5       , 0.66666667, 0.375     , 0.88888889]))

In [ ]:
#Potenciacion
w**v

array([       81,   1679616,      3125,     46656,    823543,   4782969,
              25,      4096,      6561, 134217728])

In [ ]:
#definamos los dos arreglos 2D
v = np.random.randint(low = 2, high=10, size=(3,3))
w = np.random.randint(low = 2, high=10, size=(3,3))
v,w

(array([[9, 4, 4],
        [2, 3, 2],
        [5, 2, 8]]),
 array([[9],
        [5],
        [9]]))

In [ ]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v

array([[18, 13, 13],
       [ 7,  8,  7],
       [14, 11, 17]])

In [ ]:
#multiplicacion y division
w*v

array([[16, 72, 30],
       [32, 40, 48],
       [15,  8, 18]])

In [ ]:
#Potenciacion
w**v

array([[     256, 43046721,    15625],
       [    4096,   390625,  1679616],
       [     125,       16,       81]])

## Operaciones basicas entre entre arreglos de diferente tamaño (Broadcasting)

In [ ]:
#definamos un arreglo 1D con numeros aleatorios
v = np.random.randint(low = 2, high=10, size=10)

In [ ]:
#suma y resta de un arreglo y una constante
v, v + 1 , v - 1

(array([6, 7, 3, 3, 3, 7, 6, 2, 5, 4]),
 array([7, 8, 4, 4, 4, 8, 7, 3, 6, 5]),
 array([5, 6, 2, 2, 2, 6, 5, 1, 4, 3]))

In [ ]:
#multiplicacion  y division de un arreglo y una constante
v*2 , v/2

(array([12, 14,  6,  6,  6, 14, 12,  4, 10,  8]),
 array([3. , 3.5, 1.5, 1.5, 1.5, 3.5, 3. , 1. , 2.5, 2. ]))

In [ ]:
#Comparaciones entre arreglo y una constante
v > 5

array([ True,  True, False, False, False,  True,  True, False, False,
       False])

In [ ]:
#Definamos dos arreglos con diferentes damaños
v = np.random.randint(low = 2, high=10, size=(4,4))
w = np.random.randint(low = 2, high=10, size=(1,4))
v , w

(array([[7, 6, 9, 5],
        [3, 7, 8, 7],
        [4, 9, 5, 9],
        [7, 2, 4, 6]]),
 array([[8, 4, 8, 2]]))

In [ ]:
#Suma entre los dos arreglos
w + v

array([[15, 10, 17,  7],
       [11, 11, 16,  9],
       [12, 13, 13, 11],
       [15,  6, 12,  8]])

In [ ]:
#Multiplicacion
w*v

array([[56, 24, 72, 10],
       [24, 28, 64, 14],
       [32, 36, 40, 18],
       [56,  8, 32, 12]])

In [ ]:
#exponenciacion
w**v

array([[  2097152,      4096, 134217728,        32],
       [      512,     16384,  16777216,       128],
       [     4096,    262144,     32768,       512],
       [  2097152,        16,      4096,        64]])

## Ufunctions

algunos ejemplso de Ufunctions


In [ ]:
#definamos dos arreglos 1D con numeros aleatorios
v = np.random.random(11)
v

array([0.83482342, 0.17703614, 0.485802  , 0.49303676, 0.54276901,
       0.97350625, 0.65364784, 0.60139372, 0.39760885, 0.7119198 ,
       0.87065314])

In [ ]:
v

np.float64(0.33954793807456224)

In [ ]:
#sumar las componenetes de un arreglo
np.sum(v)

np.float64(4.987578515468714)

In [ ]:
#funciones trigonometricas
np.sin(v)

array([0.49073179, 0.70398578, 0.48609365, 0.65204496, 0.30779651,
       0.83344898, 0.18372937, 0.36085563, 0.36289718, 0.80859327])

In [ ]:
#exponencial
np.exp(v)

array([1.21663483, 2.06951139, 2.01287451, 1.30119383, 1.17571005,
       1.08885525, 2.22109305, 2.43290489, 2.44638258, 1.31342242])

In [ ]:
#multiplicacion
np.multiply(v,v)

array([0.03845078, 0.52898352, 0.48938952, 0.0693175 , 0.02620263,
       0.00724659, 0.6368031 , 0.79047387, 0.80032783, 0.07433053])

In [ ]:
#media
np.mean(v)

np.float64(0.4987578515468714)

In [ ]:
#desviacion estandar
np.std(v)

np.float64(0.3120788260717778)

## Ejercicios

Para los siguientes ejercicios concidere el suguiente conjunto de datos

In [ ]:
#librearia que contiene el conjunto de tados llamados iris
from sklearn.datasets import load_iris

# **Conjunto de datos Iris**

Este conjunto de datos consta de 3 tipos diferentes de iris: (Setosa, Versicolor y Virginica) pétalo y sépalo length, almacenado en una matriz numpy.ndarray de 150x4

Las filas son las muestras y las columnas son: Longitud del sépalo, ancho del sépalo, longitud del pétalo y ancho del pétalo.

El siguiente gráfico utiliza las dos primeras características. Ver aquí para más información sobre este conjunto de datos.

In [ ]:
#utilizamos la funcion load_iris() para cargar los datos
dataset = load_iris()

In [ ]:
#Inspecciones un poco los datos , tenga encuenta que los datos vienen en forma de diccionario
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
#veamos la descripcion del data set
dataset['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

In [ ]:
X

In [ ]:
#veamos el nombre de las caracteristicas
dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
#veamos las etiquetas
dataset['filename']

'iris.csv'

In [ ]:
#separemos los datos
X = dataset['data'][: , [0,1]]

1) Obtenga el valor maximo y el valor minimo de la matriz X, luego obtenga el valor maximo y minimo de cada una de las columnas (esto es cada una de las caracteristicas)

In [ ]:
y = dataset['data'][: , [0,1]]
ww = dataset['data'][: , 0]
tt = dataset['data'][: , 1]
mm = dataset['data'][: , 2]
kk = dataset['data'][: , 3]

np.min(y)
np.min(ww)
np.min(tt)
np.min(mm)
np.min(kk)
print(np.min(y))
print(np.min(ww))
print(np.min(tt))
print(np.min(mm))
print(np.min(kk))

2.0
4.3
2.0
1.0
0.1


2) Obtenga el valor medio, la mediana, la moda y la desviacion estandar para cada una de las caracteristicas
['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
np.mean(ww)
np.mean(tt)
np.mean(mm)
np.mean(kk)
np.std(ww)
np.std(tt)
np.std(mm)
np.std(kk)

print('Media')
print(np.mean(ww))
print(np.mean(tt))
print(np.mean(mm))
print(np.mean(kk))
print('Desv')
print(np.std(ww))
print(np.std(tt))
print(np.std(mm))
print(np.std(kk))



Media
5.843333333333334
3.0573333333333337
3.7580000000000005
1.1993333333333336
Desv
0.8253012917851409
0.4344109677354946
1.759404065775303
0.7596926279021594


3) Para cada una de las caracteristicas identifique:
- la cantidad de valores mayores a las medias
- Extraiga los cuartiles de una de las variables (Recuerde que los cuartiles se calculan con los datos ordenados)

In [ ]:
a = ww[ww>np.mean(ww)]
b = tt[tt>np.mean(tt)]
c = mm[mm>np.mean(mm)]
d = kk[kk>np.mean(kk)]

print('Medida')
print(q.size)
print(e.size)
print(r.size)
print(t.size)


np.sort(kk)
Q1 = np.percentile(kk, 25)
Q2 = np.percentile(kk, 50)
Q3 = np.percentile(kk, 75)

print('cuartiles')
print(Q1)
print(Q2)
print(Q3)


Medida
70
67
93
90
cuartiles
0.3
1.3
1.8


# Bibliografia

- [Documentación Numpy](https://numpy.org/devdocs/index.html)